[debug] [2018-03-17T09:08:34.273Z] ----------------------------------------------------------------------
[debug] [2018-03-17T09:08:34.288Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Shinelon\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login --debug
[debug] [2018-03-17T09:08:34.288Z] CLI Version:   3.17.6
[debug] [2018-03-17T09:08:34.288Z] Platform:      win32
[debug] [2018-03-17T09:08:34.288Z] Node Version:  v8.9.4
[debug] [2018-03-17T09:08:34.288Z] Time:          Sat Mar 17 2018 17:08:34 GMT+0800 (中国标准时间)
[debug] [2018-03-17T09:08:34.288Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=380633398&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-03-17T09:09:09.104Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AACmswYVIyW9kVQhArlyt2t3ERbwJfe5AeOVwbwRDPZsDnPJ4KtVZNEUUCB4d64e_LaoBWge-iuvalw5goauiLs',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Sat Mar 17 2018 17:09:09 GMT+0800 (中国标准时间)
[debug] [2018-03-17T09:09:30.145Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:17)
    at Request._callback (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:34:23)
    at self.callback (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
